POST http://localhost:8000/api/ipdata
Content-Type: application/json

{
    "userip": "105.113.17.81"
}

###
POST http://localhost:8000/api/sign-up
Content-Type: application/json

{
    "username": "aady-admin",
    "email": "admin001@aady.com",
    "password": "admin001",
    "cpassword": "admin001"
}

###
POST http://localhost:8000/api/sign-in
Content-Type: application/json

{
    "username": "aady-admin",
    "password": "admin001"
}

###
PATCH  http://localhost:8000/api/aboutmepatch/648706cfb93cba72f3b1bfe2
Content-Type: application/json

{
  # "abouttext": "on Above!.",
  "vid": "ourlbbnnnmnv jhv"
}

###
POST  http://localhost:8000/api/blogclap/