POST http://localhost:8000/api/ipdata
Content-Type: application/json

{
    "userip": "105.113.17.81"
}

###
POST http://localhost:8000/api/sign-up
Content-Type: application/json

{
    "username": "aady-admin",
    "email": "admin001@aady.com",
    "password": "admin001",
    "cpassword": "admin001"
}

###
POST http://localhost:8000/api/sign-in
Content-Type: application/json

{
    "username": "aady-admin",
    "password": "admin001"
}

###
POST https://aadyportfolioapi.cyclic.app/api/sign-in
Content-Type: application/json

{
    "username": "aady-admin",
    "password": "admin001"
}

###
GET https://aadyportfolioapi.cyclic.app/api/blogget

###
GET http://localhost:8000/api/blogget

###
POST  http://localhost:8000/api/blogpost
Content-Type: application/json

{
    "title": "aa",
    "blogArticle": "adjhahhh"
}
